const K='genshin_tracker_v7';
const LEGACY_KEYS=['genshin_tracker_v6','genshin_tracker_v5'];
const D={targetName:'TSARITZA',targetDate:'2026-12-16',metaWishes:270,gems:243,wishes:68,pity:34,guaranteed:false,stardust:0,starglitter:0,stardustPink:5,stardustBlue:5,starglitterPink:0,starglitterBlue:0,history:[],incomes:[],lastScan:null};
const $=id=>document.getElementById(id), cloneDefaults=()=>JSON.parse(JSON.stringify(D));
function load(){try{let raw=localStorage.getItem(K); if(!raw) for(const k of LEGACY_KEYS){raw=localStorage.getItem(k);if(raw)break} if(!raw)return cloneDefaults();const x=JSON.parse(raw);return {...cloneDefaults(),...x,history:Array.isArray(x.history)?x.history:[],incomes:Array.isArray(x.incomes)?x.incomes:[]}}catch{return cloneDefaults()}}
let d=load();
const fmt=x=>Number(x||0).toLocaleString('es-NI'), today=()=>{const x=new Date();return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}, date=s=>{const [a,b,c]=String(s).split('-').map(Number);return new Date(a,b-1,c)}, pretty=s=>date(s).toLocaleDateString('es-NI',{day:'numeric',month:'long',year:'numeric'}), days=()=>Math.max(0,Math.ceil((date(d.targetDate)-date(today()))/86400000));
const sources={daily:'📅 Diarias',abyss:'🌌 Abismo',theater:'🎭 Teatro Imaginario',stygian:'🔥 Estigia',events:'🎉 Eventos',update:'🔄 Actualización',livestream:'📺 Livestream',anniversary:'🎂 Aniversario',quests:'📖 Misiones',exploration:'🗺️ Exploración',other:'✨ Otros'};
function save(){localStorage.setItem(K,JSON.stringify(d))}
function exchangeWishes(){const dust=Math.max(0,Math.floor(d.stardust/75))*Math.max(0,Math.min(5,d.stardustPink)+Math.min(5,d.stardustBlue)); const glitter=Math.max(0,Math.floor(d.starglitter/5))*Math.max(0,Math.min(10,d.starglitterPink)+Math.min(10,d.starglitterBlue)); return dust+glitter}
function effective(){return d.wishes+d.pity+d.gems/160+exchangeWishes()}
function calc(){const e=effective(),mw=Math.max(0,d.metaWishes-e),mg=mw*160,dy=days(),q=dy?Math.ceil(mg/dy):Math.ceil(mg),t=d.history.filter(x=>x.date===today()).reduce((s,x)=>s+Number(x.gems||0),0);return{e,mw,mg,dy,q,t,a:t-q}}
function render(){const x=calc(),pct=d.metaWishes?Math.min(100,x.e/d.metaWishes*100):0; $('targetTop').textContent=d.targetName;$('targetName').textContent=d.targetName;$('targetDate').textContent=pretty(d.targetDate);$('gems').textContent=fmt(d.gems);$('wishes').textContent=fmt(d.wishes);$('pity').textContent=`${d.pity}/90`;$('guarantee').textContent=d.guaranteed?'GARANTIZADO':'50/50';$('effective').textContent=`${x.e.toFixed(1)} deseos`;$('metaLabel').textContent=d.metaWishes;$('pct').textContent=`${pct.toFixed(1)}%`;$('bar').style.width=`${pct}%`;$('days').textContent=x.dy;$('missingGems').textContent=`Faltan ${fmt(Math.ceil(x.mg))} 💎`;$('missingWishes').textContent=`${x.mw.toFixed(1)} deseos`;$('quota').innerHTML=`${fmt(x.q)} <span>💎</span>`;$('formula').textContent=x.dy?`${fmt(Math.ceil(x.mg))} restantes ÷ ${x.dy} días`:`${fmt(Math.ceil(x.mg))} restantes`;$('base').textContent=`${fmt(x.q)} 💎`;$('ahead').textContent=`${x.a>=0?'+':''}${fmt(x.a)} 💎`;$('ahead').style.color=x.a>=0?'var(--green)':'var(--red)';$('aheadDays').textContent=x.q?(x.a/x.q).toFixed(1):'0.0';$('today').textContent=`${fmt(x.t)} 💎`;$('todayMissing').textContent=`${fmt(Math.max(0,x.q-x.t))} 💎`;$('pityLeft').textContent=`${Math.max(0,90-d.pity)} tiros`;$('reserve').textContent=`${d.metaWishes} deseos`;$('dust').textContent=fmt(d.stardust);$('glitter').textContent=fmt(d.starglitter);$('exchangeWishes').textContent=`+${exchangeWishes()} deseos`;renderHistory();renderIncome();renderPendingDaily();$('scanStatus').textContent=d.lastScan?`Último escaneo: ${pretty(d.lastScan.date)} · ${d.lastScan.found||'datos guardados'}`:'Nunca escaneado'}
function renderHistory(){const box=$('historyList');if(!d.history.length){box.innerHTML='<div class="empty">Todavía no hay registros.</div>';return}const g={};[...d.history].reverse().forEach(x=>(g[x.date]??=[]).push(x));box.innerHTML=Object.entries(g).map(([day,items])=>`<article class="history-day"><div class="between"><b>${pretty(day)}</b><span>${fmt(items.reduce((s,x)=>s+Number(x.gems||0),0))} 💎</span></div>${items.map(x=>`<div class="history-row"><span>${escapeHtml(x.note||'Movimiento')}</span><b class="${Number(x.gems||0)<0?'negative':''}">${Number(x.gems||0)>0?'+':''}${fmt(x.gems||0)} 💎</b></div>`).join('')}</article>`).join('')}
function renderIncome(){let total=0;Object.keys(sources).forEach(k=>{const n=d.incomes.filter(x=>x.source===k).reduce((s,x)=>s+Number(x.gems||0),0);total+=n;if($('sum-'+k))$('sum-'+k).textContent=`${fmt(n)} 💎`});$('incomeTotal').textContent=`${fmt(total)} 💎`}
function renderPendingDaily(){const el=$('dailyQuick');if(!el)return;const has=d.incomes.some(x=>x.source==='daily'&&x.date===today()&&x.applied!==false);el.innerHTML=has?'<div class="daily-done">✅ Diarias de hoy ya registradas.</div>':'<div class="daily-pending"><div><b>📅 Diarias de hoy</b><small>60 💎 · se suman al saldo</small></div><button type="button" class="primary small" data-action="quick-daily">＋ Añadir 60</button></div>'}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function modal(title,body,actions){$('mt').textContent=title;$('mb').innerHTML=body;$('ma').innerHTML=actions;$('dlg').showModal()}
function closeDialog(){if($('dlg').open)$('dlg').close()}
function validAmount(v){return Number.isFinite(v)&&v>0}
function addIncome({source,gems,note,applyToBalance,dateValue=today()}){const amount=Number(gems);if(!validAmount(amount))return alert('Introduce una cantidad mayor que 0.');const item={id:crypto.randomUUID?.()||String(Date.now()+Math.random()),date:dateValue,source,gems:amount,note:note||'Ingreso registrado',applied:Boolean(applyToBalance)};d.incomes.push(item);if(applyToBalance){d.gems+=amount;d.history.push({id:item.id,date:dateValue,gems:amount,note:`${sources[source]||'Ingreso'} · ${item.note}`})}save();closeDialog();render()}
function openIncomeModal(existing=false,source='daily'){modal(existing?'Registrar algo ya existente':'Registrar ingreso',`<div class="field"><label>Fuente</label><select id="src">${Object.entries(sources).map(([k,v])=>`<option value="${k}" ${k===source?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Protogemas</label><input id="iv" type="number" min="1" step="1" value="60" inputmode="numeric"></div><div class="field"><label>Fecha</label><input id="idate" type="date" value="${today()}"></div><div class="field"><label>Nota (opcional)</label><input id="inote" maxlength="100" placeholder="Ej. evento"></div><div class="notice">${existing?'Solo crea el registro; <b>no suma</b> al saldo.':'Las protogemas se <b>sumarán automáticamente</b> al saldo.'}</div>`,`<button type="button" data-action="close">Cancelar</button><button class="confirm" type="button" data-action="save-income">${existing?'Guardar registro':'Sumar y guardar'}</button>`);$('dlg').dataset.existing=existing?'1':'0'}
$('x').onclick=closeDialog;$('dlg').addEventListener('click',e=>{if(e.target===$('dlg'))closeDialog();const btn=e.target.closest('[data-action]');if(!btn)return;const a=btn.dataset.action;if(a==='close')return closeDialog();if(a==='save-income'){addIncome({source:$('src').value,gems:+$('iv').value,note:$('inote').value.trim(),applyToBalance:$('dlg').dataset.existing!=='1',dateValue:$('idate').value||today()})}if(a==='save-balance'){saveBalance();}if(a==='save-resources'){saveResources();}if(a==='save-pity'){const py=+$('py2').value;if(!Number.isFinite(py)||py<0||py>89)return alert('Pity inválido.');d.pity=py;d.guaranteed=$('gu2').value==='1';save();closeDialog();render()}if(a==='save-config'){saveConfig()}if(a==='close-day'){d.history.push({id:crypto.randomUUID?.()||String(Date.now()),date:today(),gems:0,note:'🔒 Día cerrado'});save();closeDialog();render()}})
function saveBalance(){const v=+$('v').value;if(!Number.isFinite(v)||v<0)return alert('Saldo inválido.');const gain=v-d.gems;d.gems=v;if(gain!==0)d.history.push({id:crypto.randomUUID?.()||String(Date.now()),date:today(),gems:gain,note:gain>0?'🔄 Sincronización de saldo':'🔧 Ajuste de saldo'});save();closeDialog();render()}
function saveResources(){const old={stardust:d.stardust,starglitter:d.starglitter};const vals=['sd','sg','sdp','sdb','sgp','sgb'].map(id=>+$(`${id}`).value);if(vals.some(v=>!Number.isFinite(v)||v<0))return alert('Revisa los recursos.');[d.stardust,d.starglitter,d.stardustPink,d.stardustBlue,d.starglitterPink,d.starglitterBlue]=vals;const diffDust=d.stardust-old.stardust,diffGlitter=d.starglitter-old.starglitter;if(diffDust||diffGlitter)d.history.push({id:crypto.randomUUID?.()||String(Date.now()),date:today(),gems:0,note:`💱 Recursos actualizados · Polvo ${diffDust>=0?'+':''}${diffDust} · Brillo ${diffGlitter>=0?'+':''}${diffGlitter}`});save();closeDialog();render()}
function saveConfig(){const name=$('n').value.trim()||'OBJETIVO',targetDate=$('dt').value,mw=+$('mw').value,gm=+$('gm').value,ws=+$('ws').value,py=+$('py').value;if(!targetDate||!Number.isFinite(mw)||mw<1||!Number.isFinite(gm)||gm<0||!Number.isFinite(ws)||ws<0||!Number.isFinite(py)||py<0||py>89)return alert('Revisa los valores de configuración.');d.targetName=name;d.targetDate=targetDate;d.metaWishes=mw;d.gems=gm;d.wishes=ws;d.pity=py;d.guaranteed=$('gu').value==='1';save();closeDialog();render()}
$('add').onclick=()=>modal('Registrar saldo actual',`<div class="field"><label>Protogemas actuales en el juego</label><input id="v" type="number" min="0" step="1" value="${d.gems}" inputmode="numeric"></div><div class="notice">Introduce el número exacto de Genshin. La diferencia se registra automáticamente.</div>`,`<button type="button" data-action="close">Cancelar</button><button class="confirm" type="button" data-action="save-balance">Guardar saldo</button>`);
$('addIncome').onclick=()=>openIncomeModal(false);$('addExisting').onclick=()=>openIncomeModal(true);
$('resourcesBtn').onclick=()=>modal('Recursos convertibles',`<div class="field"><label>✨ Polvo estelar</label><input id="sd" type="number" min="0" value="${d.stardust}"></div><div class="field"><label>🌟 Brillo estelar</label><input id="sg" type="number" min="0" value="${d.starglitter}"></div><div class="grid two"><div class="field"><label>Polvo → Intertwined</label><input id="sdp" type="number" min="0" max="5" value="${d.stardustPink}"></div><div class="field"><label>Polvo → Acquaint</label><input id="sdb" type="number" min="0" max="5" value="${d.stardustBlue}"></div><div class="field"><label>Brillo → Intertwined</label><input id="sgp" type="number" min="0" max="10" value="${d.starglitterPink}"></div><div class="field"><label>Brillo → Acquaint</label><input id="sgb" type="number" min="0" max="10" value="${d.starglitterBlue}"></div></div><div class="notice">El cálculo usa 75 Polvo por destino y 5 Brillos por destino. Puedes elegir cuántos intercambios mensuales quieres contar como disponibles.</div>`,`<button type="button" data-action="close">Cancelar</button><button class="confirm" type="button" data-action="save-resources">Guardar recursos</button>`);
$('config').onclick=()=>modal('Configuración',`<div class="field"><label>Objetivo</label><input id="n" maxlength="40" value="${escapeHtml(d.targetName)}"></div><div class="field"><label>Fecha límite</label><input id="dt" type="date" value="${d.targetDate}"></div><div class="field"><label>Meta de seguridad (deseos efectivos)</label><input id="mw" type="number" min="1" value="${d.metaWishes}"></div><div class="field"><label>Protogemas</label><input id="gm" type="number" min="0" value="${d.gems}"></div><div class="field"><label>Deseos</label><input id="ws" type="number" min="0" value="${d.wishes}"></div><div class="field"><label>Pity (0–89)</label><input id="py" type="number" min="0" max="89" value="${d.pity}"></div><div class="field"><label>Próximo 5★</label><select id="gu"><option value="0" ${!d.guaranteed?'selected':''}>50/50</option><option value="1" ${d.guaranteed?'selected':''}>Garantizado</option></select></div>`,`<button type="button" data-action="close">Cancelar</button><button class="confirm" type="button" data-action="save-config">Guardar</button>`);
$('pityBtn').onclick=()=>modal('Actualizar pity',`<div class="field"><label>Pity actual (0–89)</label><input id="py2" type="number" min="0" max="89" value="${d.pity}"></div><div class="field"><label>Próximo 5★</label><select id="gu2"><option value="0" ${!d.guaranteed?'selected':''}>50/50</option><option value="1" ${d.guaranteed?'selected':''}>Garantizado</option></select></div>`,`<button type="button" data-action="close">Cancelar</button><button class="confirm" type="button" data-action="save-pity">Guardar</button>`);
$('close').onclick=()=>modal('Cerrar día',`<div class="notice">¿Quieres cerrar ${pretty(today())}? El cierre no modifica tu saldo.</div>`,`<button type="button" data-action="close">Cancelar</button><button class="confirm" type="button" data-action="close-day">Cerrar día</button>`);
$('undo').onclick=()=>{if(!d.history.length)return alert('No hay movimientos para deshacer.');const h=d.history.pop();if(h.gems){d.gems=Math.max(0,d.gems-h.gems);const inc=d.incomes.find(x=>x.id===h.id);if(inc)inc.applied=false}save();render()};$('clear').onclick=()=>{if(confirm('¿Limpiar todo el historial? Esto no cambiará tu saldo ni borrará tus ingresos.')){d.history=[];save();render()}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`genshin-tracker-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('import').onclick=()=>$('file').click();$('file').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||typeof x!=='object')throw 0;if(!confirm('¿Importar este respaldo y reemplazar los datos actuales?'))return;d={...cloneDefaults(),...x,history:Array.isArray(x.history)?x.history:[],incomes:Array.isArray(x.incomes)?x.incomes:[]};save();render();alert('Respaldo importado correctamente.')}catch{alert('El archivo no es un respaldo JSON válido.')}};r.readAsText(f);e.target.value=''};$('reset').onclick=()=>{if(confirm('Esto borrará el tracker local. ¿Continuar?')){d=cloneDefaults();save();render()}};
$('dailyQuick').addEventListener('click',e=>{if(e.target.closest('[data-action="quick-daily"]'))addIncome({source:'daily',gems:60,note:'Diarias de hoy',applyToBalance:true})});
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(btn.dataset.tab).classList.add('active')});document.querySelectorAll('.income-card').forEach(card=>card.onclick=()=>{const src=card.dataset.source,items=d.incomes.filter(x=>x.source===src),total=items.reduce((s,x)=>s+Number(x.gems||0),0);modal(sources[src],`<div class="source-total">${fmt(total)} 💎</div>`+(items.length?items.slice().reverse().map(x=>`<div class="income-row"><span>${pretty(x.date)}<small>${escapeHtml(x.note||'')}</small></span><b>+${fmt(x.gems)} 💎</b></div>`).join(''):'<div class="empty">Todavía no hay registros para esta fuente.</div>'),`<button type="button" class="confirm" data-action="close">Cerrar</button>`) });
// Captura/OCR: usa TextDetector si el navegador lo ofrece; si no, permite introducir los valores detectados manualmente.
$('scanBtn').onclick=()=>openScan();
$('scanFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;await processScan(f);e.target.value=''};
async function openScan(){modal('📷 Escanear recursos',`<div class="notice">Haz una captura donde se vean tus <b>Protogemas, Polvo estelar y Brillo estelar</b>. La app intentará leer los números. Si tu navegador no tiene OCR integrado, te mostrará un formulario de confirmación.</div><div class="field"><label>Selecciona captura</label><input id="scanLocal" type="file" accept="image/*"></div><div id="ocrResult" class="scan-result"></div>`,`<button type="button" data-action="close">Cancelar</button>`);$('scanLocal').onchange=async e=>{const f=e.target.files[0];if(f)await processScan(f)} }
async function processScan(file){$('ocrResult').innerHTML='<div class="notice">🔎 Analizando captura…</div>';let found={};try{if('TextDetector' in window){const bmp=await createImageBitmap(file);const detector=new TextDetector();const blocks=await detector.detect(bmp);const text=blocks.map(b=>b.rawValue).join(' ');found=parseNumbers(text)}else{throw new Error('OCR no disponible')}}catch{found={}}renderScanForm(found)}
function parseNumbers(text){const nums=(text.match(/\b\d{1,7}\b/g)||[]).map(Number);return{gems:nums[0]??d.gems,stardust:nums[1]??d.stardust,starglitter:nums[2]??d.starglitter,raw:text}}
function renderScanForm(found){$('ocrResult').innerHTML=`<div class="notice">${found.raw?'Texto detectado. Confirma antes de guardar.':'OCR automático no está disponible en este navegador. Introduce los tres valores de la captura.'}</div><div class="field"><label>💎 Protogemas</label><input id="sgems" type="number" min="0" value="${found.gems??d.gems}"></div><div class="field"><label>✨ Polvo estelar</label><input id="sdust" type="number" min="0" value="${found.stardust??d.stardust}"></div><div class="field"><label>🌟 Brillo estelar</label><input id="sglitter" type="number" min="0" value="${found.starglitter??d.starglitter}"></div><button type="button" class="confirm" id="applyScan">Guardar y sincronizar</button>`;$('applyScan').onclick=()=>{const ng=+$('sgems').value,nsd=+$('sdust').value,nsg=+$('sglitter').value;if([ng,nsd,nsg].some(v=>!Number.isFinite(v)||v<0))return alert('Valores inválidos.');const diff=ng-d.gems;d.gems=ng;d.stardust=nsd;d.starglitter=nsg;if(diff)d.history.push({id:crypto.randomUUID?.()||String(Date.now()),date:today(),gems:diff,note:diff>0?'📷 Escaneo · aumento de saldo':'📷 Escaneo · ajuste de saldo'});d.lastScan={date:today(),found:`💎 ${fmt(ng)} · ✨ ${fmt(nsd)} · 🌟 ${fmt(nsg)}`};save();closeDialog();render()}}
$('resourcesBtn').addEventListener('click',()=>{});
document.querySelectorAll('.income-card').forEach(card=>card.setAttribute('role','button'));
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
render();
